# Generated by ChemEFlow
# Change the values in INPUTS and run the file again.

import numpy as np
import pandas as pd

# ---------------- INPUTS ----------------
v_1_totalflow = 1000  # 1 · Total mass flow
v_1_a_fraction = 0.85  # 1 · A · Mass fraction
v_1_w_fraction = 0.15  # 1 · W · Mass fraction
v_4_e_fraction = 1  # 4 · E · Mass fraction
v_5_e_componentflow = 0  # 5 · E · Component mass flow
v_6_a_fraction = 0.01  # 6 · A · Mass fraction
v_6_w_fraction = 0.99  # 6 · W · Mass fraction

# --------- INITIAL CALCULATIONS ---------
# 4: zero remaining composition
# Remaining unspecified fractions are zero for the exported solved case.
v_4_a_fraction = 0.0
v_4_w_fraction = 0.0

# ṁT × w1
v_1_a_componentflow = v_1_totalflow * v_1_a_fraction

# ṁT × w2
v_1_w_componentflow = v_1_totalflow * v_1_w_fraction

# Composition closure: 1 − sum of specified fractions
v_1_e_fraction = 1 - (v_1_a_fraction + v_1_w_fraction)

# ṁT × w3
v_1_e_componentflow = v_1_totalflow * v_1_e_fraction

# Composition closure: 1 − sum of specified fractions
v_6_e_fraction = 1 - (v_6_a_fraction + v_6_w_fraction)


# ---------- TARGET FUNCTIONS -----------
def target_m_t_2_eq_1(v_1_totalflow):
    return 0.5 * v_1_totalflow

def target_w_1_2_eq_2(v_1_a_fraction):
    return v_1_a_fraction

def target_w_2_2_eq_3(v_1_w_fraction):
    return v_1_w_fraction

def target_x_a_r1_eq_12(extent_of_reaction, v_1_a_componentflow, v_2_a_componentflow):
    return 92 * extent_of_reaction / (v_1_a_componentflow + v_2_a_componentflow)

def target_x_a_global_eq_13(v_1_a_componentflow, v_6_a_componentflow):
    return (v_1_a_componentflow - v_6_a_componentflow) / v_1_a_componentflow

def target_m_1_5_eq_10(v_2_totalflow, v_2_a_fraction, v_6_a_fraction, v_6_totalflow):
    return v_2_totalflow * v_2_a_fraction + v_6_a_fraction * v_6_totalflow

def target_m_2_3_eq_8(v_5_totalflow, v_5_a_componentflow):
    return v_5_totalflow - v_5_a_componentflow

def target_m_1_3_eq_7(v_5_a_componentflow):
    return v_5_a_componentflow

# ----------- SOLVE SEQUENCE ------------
# m_T_2 (Eq. 1)
v_2_totalflow = target_m_t_2_eq_1(v_1_totalflow)

# w_1_2 (Eq. 2)
v_2_a_fraction = target_w_1_2_eq_2(v_1_a_fraction)

# w1 × ṁT
v_2_a_componentflow = v_2_totalflow * v_2_a_fraction

# w_2_2 (Eq. 3)
v_2_w_fraction = target_w_2_2_eq_3(v_1_w_fraction)

# w2 × ṁT
v_2_w_componentflow = v_2_totalflow * v_2_w_fraction

# 1 − sum of the other fractions
v_2_e_fraction = 1 - (v_2_a_fraction + v_2_w_fraction)

# Total flow − sum of the other component flows
v_2_e_componentflow = v_2_totalflow - (v_2_a_componentflow + v_2_w_componentflow)

# Linear System (Eqs. 4-6, 9, 11)
A_1 = np.array([
    [92, 0, 0, 0, v_6_a_fraction],
    [-18, 0, 0, 0, v_6_w_fraction],
    [0, 0, 1, 0, 1],
    [0, 1, -1, -1, 0],
    [0, 0, 0, 1, -1]
], dtype=float)
b_1 = np.array([v_1_a_componentflow, v_1_w_componentflow, v_1_totalflow, 0, v_2_totalflow], dtype=float)
x_1 = np.linalg.solve(A_1, b_1)
extent_of_reaction = x_1[0]
v_3_totalflow = x_1[1]
v_4_totalflow = x_1[2]
v_5_totalflow = x_1[3]
v_6_totalflow = x_1[4]

# w1 × ṁT
v_4_a_componentflow = v_4_totalflow * v_4_a_fraction

# w2 × ṁT
v_4_w_componentflow = v_4_totalflow * v_4_w_fraction

# w3 × ṁT
v_4_e_componentflow = v_4_totalflow * v_4_e_fraction

# ṁ3 / ṁT
v_5_e_fraction = v_5_e_componentflow / v_5_totalflow

# w1 × ṁT
v_6_a_componentflow = v_6_totalflow * v_6_a_fraction

# w2 × ṁT
v_6_w_componentflow = v_6_totalflow * v_6_w_fraction

# w3 × ṁT
v_6_e_componentflow = v_6_totalflow * v_6_e_fraction

# X_A_R1 (Eq. 12)
a_conversion_in_the_reactor = target_x_a_r1_eq_12(extent_of_reaction, v_1_a_componentflow, v_2_a_componentflow)

# X_A_Global (Eq. 13)
a_conversion_in_the_global_system = target_x_a_global_eq_13(v_1_a_componentflow, v_6_a_componentflow)

# m_1_5 (Eq. 10)
v_5_a_componentflow = target_m_1_5_eq_10(v_2_totalflow, v_2_a_fraction, v_6_a_fraction, v_6_totalflow)

# ṁ1 / ṁT
v_5_a_fraction = v_5_a_componentflow / v_5_totalflow

# 1 − sum of the other fractions
v_5_w_fraction = 1 - (v_5_a_fraction + v_5_e_fraction)

# Total flow − sum of the other component flows
v_5_w_componentflow = v_5_totalflow - (v_5_a_componentflow + v_5_e_componentflow)

# m_2_3 (Eq. 8)
v_3_w_componentflow = target_m_2_3_eq_8(v_5_totalflow, v_5_a_componentflow)

# ṁ2 / ṁT
v_3_w_fraction = v_3_w_componentflow / v_3_totalflow

# m_1_3 (Eq. 7)
v_3_a_componentflow = target_m_1_3_eq_7(v_5_a_componentflow)

# ṁ1 / ṁT
v_3_a_fraction = v_3_a_componentflow / v_3_totalflow

# 1 − sum of the other fractions
v_3_e_fraction = 1 - (v_3_a_fraction + v_3_w_fraction)

# Total flow − sum of the other component flows
v_3_e_componentflow = v_3_totalflow - (v_3_a_componentflow + v_3_w_componentflow)

# ------------- RESULTS -----------------
defined_variables = pd.DataFrame([
    ["A conversion in the global system", a_conversion_in_the_global_system, "dimensionless", "solved", "Calculated by X_A_Global (Eq. 13)"],
    ["A conversion in the reactor", a_conversion_in_the_reactor, "dimensionless", "solved", "Calculated by X_A_R1 (Eq. 12)"],
    ["Extent of reaction", extent_of_reaction, "kmol/h", "solved", "Solved by Linear System (Eqs. 4-6, 9, 11)"]
], columns=["Name", "Value", "Unit", "Status", "Origin block"])
print("\nDefined variables")
print(defined_variables.to_string(index=False))

# Mass Composition [dimensionless]
masscomposition_values = np.array([
    [v_1_a_fraction, v_2_a_fraction, v_3_a_fraction, v_4_a_fraction, v_5_a_fraction, v_6_a_fraction],
    [v_1_w_fraction, v_2_w_fraction, v_3_w_fraction, v_4_w_fraction, v_5_w_fraction, v_6_w_fraction],
    [v_1_e_fraction, v_2_e_fraction, v_3_e_fraction, v_4_e_fraction, v_5_e_fraction, v_6_e_fraction]
], dtype=float)
masscomposition_values = np.vstack([masscomposition_values, masscomposition_values.sum(axis=0, keepdims=True)])
masscomposition = pd.DataFrame(
    masscomposition_values,
    index=["A","W","E","Total"],
    columns=["1","2","3","4","5","6"],
)
print("\nMass Composition [dimensionless]")
print(masscomposition.to_string())

# Mass Flow [kg/h]
massflow_values = np.array([
    [v_1_a_componentflow, v_2_a_componentflow, v_3_a_componentflow, v_4_a_componentflow, v_5_a_componentflow, v_6_a_componentflow],
    [v_1_w_componentflow, v_2_w_componentflow, v_3_w_componentflow, v_4_w_componentflow, v_5_w_componentflow, v_6_w_componentflow],
    [v_1_e_componentflow, v_2_e_componentflow, v_3_e_componentflow, v_4_e_componentflow, v_5_e_componentflow, v_6_e_componentflow]
], dtype=float)
massflow_values = np.vstack([massflow_values, massflow_values.sum(axis=0, keepdims=True)])
massflow = pd.DataFrame(
    massflow_values,
    index=["A","W","E","Total"],
    columns=["1","2","3","4","5","6"],
)
print("\nMass Flow [kg/h]")
print(massflow.to_string())

# Molar Composition [dimensionless]
molarcomposition_values = np.array([
    [((v_1_a_componentflow / 46) / ((v_1_a_componentflow / 46) + (v_1_w_componentflow / 18) + (v_1_e_componentflow / 74))), ((v_2_a_componentflow / 46) / ((v_2_a_componentflow / 46) + (v_2_w_componentflow / 18) + (v_2_e_componentflow / 74))), ((v_3_a_componentflow / 46) / ((v_3_a_componentflow / 46) + (v_3_w_componentflow / 18) + (v_3_e_componentflow / 74))), ((v_4_a_componentflow / 46) / ((v_4_a_componentflow / 46) + (v_4_w_componentflow / 18) + (v_4_e_componentflow / 74))), ((v_5_a_componentflow / 46) / ((v_5_a_componentflow / 46) + (v_5_w_componentflow / 18) + (v_5_e_componentflow / 74))), ((v_6_a_componentflow / 46) / ((v_6_a_componentflow / 46) + (v_6_w_componentflow / 18) + (v_6_e_componentflow / 74)))],
    [((v_1_w_componentflow / 18) / ((v_1_a_componentflow / 46) + (v_1_w_componentflow / 18) + (v_1_e_componentflow / 74))), ((v_2_w_componentflow / 18) / ((v_2_a_componentflow / 46) + (v_2_w_componentflow / 18) + (v_2_e_componentflow / 74))), ((v_3_w_componentflow / 18) / ((v_3_a_componentflow / 46) + (v_3_w_componentflow / 18) + (v_3_e_componentflow / 74))), ((v_4_w_componentflow / 18) / ((v_4_a_componentflow / 46) + (v_4_w_componentflow / 18) + (v_4_e_componentflow / 74))), ((v_5_w_componentflow / 18) / ((v_5_a_componentflow / 46) + (v_5_w_componentflow / 18) + (v_5_e_componentflow / 74))), ((v_6_w_componentflow / 18) / ((v_6_a_componentflow / 46) + (v_6_w_componentflow / 18) + (v_6_e_componentflow / 74)))],
    [((v_1_e_componentflow / 74) / ((v_1_a_componentflow / 46) + (v_1_w_componentflow / 18) + (v_1_e_componentflow / 74))), ((v_2_e_componentflow / 74) / ((v_2_a_componentflow / 46) + (v_2_w_componentflow / 18) + (v_2_e_componentflow / 74))), ((v_3_e_componentflow / 74) / ((v_3_a_componentflow / 46) + (v_3_w_componentflow / 18) + (v_3_e_componentflow / 74))), ((v_4_e_componentflow / 74) / ((v_4_a_componentflow / 46) + (v_4_w_componentflow / 18) + (v_4_e_componentflow / 74))), ((v_5_e_componentflow / 74) / ((v_5_a_componentflow / 46) + (v_5_w_componentflow / 18) + (v_5_e_componentflow / 74))), ((v_6_e_componentflow / 74) / ((v_6_a_componentflow / 46) + (v_6_w_componentflow / 18) + (v_6_e_componentflow / 74)))]
], dtype=float)
molarcomposition_values = np.vstack([molarcomposition_values, molarcomposition_values.sum(axis=0, keepdims=True)])
molarcomposition = pd.DataFrame(
    molarcomposition_values,
    index=["A","W","E","Total"],
    columns=["1","2","3","4","5","6"],
)
print("\nMolar Composition [dimensionless]")
print(molarcomposition.to_string())

# Molar Flow [kmol/h]
molarflow_values = np.array([
    [(v_1_a_componentflow / 46), (v_2_a_componentflow / 46), (v_3_a_componentflow / 46), (v_4_a_componentflow / 46), (v_5_a_componentflow / 46), (v_6_a_componentflow / 46)],
    [(v_1_w_componentflow / 18), (v_2_w_componentflow / 18), (v_3_w_componentflow / 18), (v_4_w_componentflow / 18), (v_5_w_componentflow / 18), (v_6_w_componentflow / 18)],
    [(v_1_e_componentflow / 74), (v_2_e_componentflow / 74), (v_3_e_componentflow / 74), (v_4_e_componentflow / 74), (v_5_e_componentflow / 74), (v_6_e_componentflow / 74)]
], dtype=float)
molarflow_values = np.vstack([molarflow_values, molarflow_values.sum(axis=0, keepdims=True)])
molarflow = pd.DataFrame(
    molarflow_values,
    index=["A","W","E","Total"],
    columns=["1","2","3","4","5","6"],
)
print("\nMolar Flow [kmol/h]")
print(molarflow.to_string())
